name: Maven CI/CD

on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 18
      uses: actions/setup-java@v1
      with:
        java-version: 18
        
    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2  

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
    - name: CINotify Email
      uses: cinotify/github-action@v1.1.0
      with:
          to: 'shipravalecha92@gmail.com'
          subject: 'build successful'
          body: 'This is a notification from GitHub actions.'

